# Generated by Django 4.2.1 on 2023-05-24 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-title',), 'verbose_name_plural': 'Categories'},
        ),
    ]
