# fly.toml app configuration file generated for tobietopia on 2023-06-11T17:10:11+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tobietopia"
primary_region = "jnb"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
